import json
from typing import Any, Dict, List, Optional, Tuple


class BidGenerator:
    """
    Workspace 3: Automated Bid Generation Agent.
    Maps RFP requirements to knowledge base capabilities and produces a draft.
    """

    def __init__(self, knowledge_hub_path: str):
        with open(knowledge_hub_path, "r", encoding="utf-8") as f:
            self.hub = json.load(f)

    def generate_compliance_matrix(self, blueprint: Dict[str, Any]) -> Tuple[str, List[str]]:
        """
        Generate markdown matrix and risk list from features + mandatory clauses.
        """
        features = blueprint.get("features", [])
        star_clauses = blueprint.get("star_clauses", [])
        matrix: List[str] = []
        risks: List[str] = []

        matrix.append("| ID | Requirement Type | Detail | Company Capability | Status |")
        matrix.append("| :--- | :--- | :--- | :--- | :--- |")

        for feat in features:
            req_name = feat.get("name", "Unknown requirement")
            match = self._find_best_match(req_name)
            status = "FULLY MET" if match else "PARTIAL / CUSTOM"
            matrix.append(
                f"| {feat.get('id', '?')} | Feature | {req_name} | "
                f"{match.get('name') if match else 'Custom Development'} | {status} |"
            )

        for clause in star_clauses:
            match = self._find_best_match(clause)
            if not match:
                risks.append(f"CRITICAL: no matching capability for mandatory clause: {clause}")
                status = "VOLATILE"
            else:
                status = "COMPLIANT"
            matrix.append(
                f"| * | Mandatory | {clause} | {match.get('name') if match else 'None'} | {status} |"
            )

        return "\n".join(matrix), risks

    def _find_best_match(self, requirement: str) -> Optional[Dict[str, Any]]:
        req_lower = requirement.lower()
        for product in self.hub.get("products", []):
            name_hit = req_lower in product.get("name", "").lower()
            feature_hit = any(
                f.lower() in req_lower for f in product.get("specs", {}).get("features", [])
            )
            if name_hit or feature_hit:
                return product
        return None

    def export_bid_draft(
        self,
        blueprint: Dict[str, Any],
        matrix: str,
        risks: List[str],
        output_path: str,
        industry_context: str = "",
    ) -> str:
        industry = blueprint.get("metadata", {}).get("industry", "Unknown")
        style_hint = blueprint.get("ui_style_hint", "Sci-Fi")
        risk_section = "\n".join([f"- {r}" for r in risks]) if risks else "- No critical * risks detected."

        draft = f"""# Bid Draft - {industry}

## 1. Industry Context & Social Intelligence
{industry_context}

## 2. Compliance Matrix
{matrix}

## 3. Critical Risk Control
{risk_section}

## 4. Demo Recommendations
- Suggested style template: {style_hint}
- Priority: demonstrate mandatory (*) clauses first.

---
Generated by PreBid Master AI.
"""
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(draft)
        return output_path


if __name__ == "__main__":
    mock_blueprint = {
        "metadata": {"industry": "Smart Campus"},
        "features": [
            {"id": 1, "name": "Face Scoring & Quality Filtering", "description": "xxx"},
            {"id": 2, "name": "Campus Security Management", "description": "xxx"},
        ],
        "star_clauses": ["Support motion face detection and best-frame output"],
    }

    gen = BidGenerator(r"e:\dailm---distributed-ai-labor-market\vault\knowledge_hub.json")
    matrix_md, risk_list = gen.generate_compliance_matrix(mock_blueprint)
    path = gen.export_bid_draft(mock_blueprint, matrix_md, risk_list, "BID_DRAFT_HAINAN_TEST.md")
    print(f"Bid draft generated at: {path}")
